services:
  app:
    container_name: app
    build: ./web_app
    command: python ./web_app/controller.py
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - .:/web_app
    environment:
       MONGO_LANG_DBNAME : language
       MONGO_TEXT_DBNAME : text
       MONGO_USER : admin
       MONGO_PASS : 123456
  db:
    container_name: db
    image: mongo:latest
    volumes:
      - ./db/languages.js:/docker-entrypoint-languages.d/languages.js:ro 
    ports:
      - "27017:27017"
